### PR TITLE
feat: Adds support for project.json dependency files.

### PR DESCRIPTION
**Pull request by RyanHavoc**
- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/broker/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

This PR adds support for project.json dotnet dependencies.

#### Where should the reviewer start?

Fire up a local Broker for any of the SCMs and add a repo containing a project.json file. Do a search for snyk-fixtures/dotnet-project-json, there is a repo for GitHub, GitHub Enterprise, Bitbucket Server and GitLab for testing.

#### How should this be manually tested?

I've tested this for each SCM but to test manually yourself try adding a repo containing a project.json using a Broker for each SCM.

### CODE REVIEW

**Comment by darscan** [comment]
We discussed whether or not to include links to internal systems (e.g. Jira) from open source repos (like this one) a while back, and I'm not sure what we decided, but in my opinion we probably shouldn't.

**Comment by RyanHavoc** [comment]
@darscan I've rebased the commit message now. This PR only adds in project.json support. I haven't added anything for Jira?

**Comment by darscan** [comment]
@RyanHavoc Coolio. Regarding Jira, I was talking about the link in the PR description

**Comment by RyanHavoc** [comment]
@darscan Ah, fair enough. I've removed it.

**Pull request merged**
